version: '3.10'
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - ${DB_HOST:-127.0.0.1}:${DB_PORT:-5432}:5432
    environment:
      POSTGRES_DB: ${DB_NAME:?err}
      POSTGRES_USER: ${DB_USER:?err}
      POSTGRES_PASSWORD: ${DB_PASS:?err}
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:7.0.7-alpine
    ports:
      - 127.0.0.1:6379:6379
  api:
    image: node-messenger:latest
    scale: 3
    ports:
      - 3000
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      DB_HOST: db
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - 127.0.0.1:3000:3000

volumes:
  db:
