version: '3.10'
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - ${DB_HOST:-127.0.0.1}:${DB_PORT:-5432}:5432
    environment:
      POSTGRES_DB: ${DB_NAME:?err}
      POSTGRES_USER: ${DB_USER:?err}
      POSTGRES_PASSWORD: ${DB_PASS:?err}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
